{
 "title": "Callback API dashboatrd",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "External IO Exception Rate(No of exceptions / sec)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (service_name)(rate(callback_api_external_io_exception_type[2m]))"
    }
   ]
  },
  {
   "title": "External IO Exception Rate(No of exceptions / sec)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(callback_api_http_requests_exception_type[2m]))"
    }
   ]
  },
  {
   "title": "External IO rate / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "IO per sec" }
   ],
   "targets": [
    {
     "expr": "sum by (service_name)(rate(callback_api_external_io_duration_ms_count[2m]))"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "locale", "label": "Requests per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(callback_api_http_requests_total[2m]))"
    }
   ]
  },
  {
   "title": "average response time External IO ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (service_name, status)(rate(callback_api_external_io_duration_ms_sum[2m]))\n /\nsum by (service_name, status)(rate(callback_api_external_io_duration_ms_count[2m]))"
    }
   ]
  },
  {
   "title": "Average Response Time ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(callback_api_http_requests_duration_ms_sum[2m]))\n /\nsum(rate(callback_api_http_requests_duration_ms_count[2m]))"
    }
   ]
  },
  {
   "title": "Average response time status wise",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code)(irate(callback_api_http_requests_duration_ms_sum[2m]))\n /\nsum by (status_code)(irate(callback_api_http_requests_duration_ms_count[2m]))"
    }
   ]
  },
  {
   "title": "Response time distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Requests per sec" }
   ],
   "targets": [
    {
     "expr": "sum by (le)(rate(callback_api_http_requests_duration_ms_bucket[2m]))"
    }
   ]
  },
  {
   "title": "Error rate (500 status code)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(callback_api_http_requests_duration_ms_count{status_code='5xx'}[2m]))"
    }
   ]
  },
  {
   "title": "External IO distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (le)(rate(callback_api_external_io_duration_ms_bucket[2m]))"
    }
   ]
  },
  {
   "title": "Response Time Absolute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "callback_api_http_requests_duration_ms_total"
    }
   ]
  },
  {
   "title": "90% SLO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    {
     "format": "short",
     "label": "Fraction of requests rate in 500 ms bucket"
    }
   ],
   "targets": [
    {
     "expr": "sum(rate(callback_api_http_requests_duration_ms_bucket{le=\"0.05\"}[2m]))\n/\n  sum(rate(callback_api_http_requests_duration_ms_count[2m]))"
    }
   ]
  }
 ]
}