{
 "title": "CLI dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "app_name", "query": "label_values(app_name)" },
   {
    "name": "server",
    "query": "label_values({app_name=~\"$app_name\"}, server_ip)"
   },
   {
    "name": "entry_point",
    "query": "label_values({app_name=~\"$app_name\", server_ip=~\"$server\"}, entry_point)"
   },
   { "name": "slo_duration_sec", "query": "label_values(le)" },
   { "name": "io_tag", "query": "label_values(tag)" }
  ]
 },
 "panels": [
  {
   "title": "Average Response Time ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (entry_point, function_name, status)(rate(function_duration_ms_sum{app_name=~\"$app_name\", server_ip=~\"$server\", entry_point=~\"$entry_point\"}[2m]))\n /\nsum by (entry_point, function_name, status)(rate(function_duration_ms_count{app_name=~\"$app_name\", server_ip=~\"$server\", entry_point=~\"$entry_point\"}[2m]))"
    }
   ]
  },
  {
   "title": "Absolute Response Time ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "function_duration_ms_total{app_name=~\"$app_name\", server_ip=~\"$server\", entry_point=~\"$entry_point\"}"
    }
   ]
  },
  {
   "title": "Average Response Time External IO ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (entry_point, name, tag)(rate(external_io_duration_ms_sum{app_name=~\"$app_name\", server_ip=~\"$server\", entry_point=~\"$entry_point\", tag=~\"$io_tag\"}[2m]))\n /\nsum by (entry_point, name, tag)(rate(external_io_duration_ms_count{app_name=~\"$app_name\", server_ip=~\"$server\", entry_point=~\"$entry_point\", tag=~\"$io_tag\"}[2m]))",
     "legendFormat": "{{entry_point}} -- {{name}} -- {{tag}}"
    }
   ]
  },
  {
   "title": "Function Exception Rate (per sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (function_name)(rate(function_exception_type{app_name=~\"$app_name\", server_ip=~\"$server\", entry_point=~\"$entry_point\"}[2m]))"
    }
   ]
  },
  {
   "title": "Average Request Rate ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (entry_point, function_name, status)(rate(function_duration_ms_count{app_name=~\"$app_name\", server_ip=~\"$server\", entry_point=~\"$entry_point\"}[2m]))"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "function_duration_ms_count{app_name=~\"$app_name\", server_ip=~\"$server\", entry_point=~\"$entry_point\"}"
    }
   ]
  },
  {
   "title": "External IO rate / sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "IO per sec" }
   ],
   "targets": [
    {
     "expr": "sum by (entry_point, name, tag)(rate(external_io_duration_ms_count{app_name=~\"$app_name\", server_ip=~\"$server\", entry_point=~\"$entry_point\", tag=~ \"$io_tag\"}[2m]))",
     "legendFormat": "{{entry_point}}----{{name}}--{{tag}}}}"
    }
   ]
  }
 ]
}