{
 "title": "API dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "External IO excepetion",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "External IO rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "IO per sec" }
   ],
   "targets": [
    {
     "expr": "sum by (service_name)(rate(myoperator_external_io_duration_ms_count[2m]))"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "locale", "label": "Requests per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(myoperator_http_requests_total[2m]))"
    }
   ]
  },
  {
   "title": "average response time External IO ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (service_name, status)(rate(myoperator_external_io_duration_ms_sum[2m]))\n /\nsum by (service_name, status)(rate(myoperator_external_io_duration_ms_count[2m]))"
    }
   ]
  },
  {
   "title": "Average Response Time ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(myoperator_http_requests_duration_ms_sum[2m]))\n /\nsum(rate(myoperator_http_requests_duration_ms_count[2m]))"
    }
   ]
  },
  {
   "title": "Average response time status wise",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code)(irate(myoperator_http_requests_duration_ms_sum[2m]))\n /\nsum by (status_code)(irate(myoperator_http_requests_duration_ms_count[2m]))"
    }
   ]
  },
  {
   "title": "Response time distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Requests per sec" }
   ],
   "targets": [
    {
     "expr": "sum by (le)(rate(myoperator_http_requests_duration_ms_bucket[2m]))"
    }
   ]
  },
  {
   "title": "Error rate (500 status code)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(myoperator_http_requests_duration_ms_count{status_code='5xx'}[2m]))"
    }
   ]
  },
  {
   "title": "External IO distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (le)(rate(myoperator_external_io_duration_ms_bucket[2m]))"
    }
   ]
  },
  {
   "title": "Response Time Absolute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "myoperator_http_requests_duration_ms_total"
    }
   ]
  },
  {
   "title": "90% SLO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    {
     "format": "short",
     "label": "Fraction of requests rate in 500 ms bucket"
    }
   ],
   "targets": [
    {
     "expr": "sum(rate(myoperator_http_requests_duration_ms_bucket{le=\"0.5\"}[2m])) by (job)\n/\n  sum(rate(myoperator_http_requests_duration_ms_count[2m])) by (job)"
    }
   ]
  }
 ]
}