{
 "title": "Tagged APM dashboatrd 1",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "app_name", "query": "label_values(app_name)" },
   {
    "name": "server",
    "query": "label_values({app_name=~\"$app_name\"}, server_ip)"
   },
   {
    "name": "entry_point",
    "query": "label_values({app_name=~\"$app_name\", server_ip=~\"$server\"}, entry_point)"
   },
   { "name": "slo_duration_sec", "query": "label_values(le)" },
   { "name": "io_tag", "query": "label_values(tag)" }
  ]
 },
 "panels": [
  {
   "title": "External Service Exception Rate(No of exceptions / sec)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (service_name)(rate(external_io_exception_type{app_name=~\"$app_name\", server_ip=~\"$server\", entry_point=~\"$entry_point\"}[2m]))"
    }
   ]
  },
  {
   "title": "Http Requests Exception Rate(No of exceptions / sec)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum by (service_name)(rate(http_requests_exception_type{app_name=~\"$app_name\", server_ip=~\"$server\", entry_point=~\"$entry_point\"}[2m]))"
    }
   ]
  },
  {
   "title": "External IO rate / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "IO per sec" }
   ],
   "targets": [
    {
     "expr": "sum by (entry_point, name, tag)(rate(external_io_duration_ms_count{app_name=~\"$app_name\", server_ip=~\"$server\", entry_point=~\"$entry_point\", tag=~ \"$io_tag\"}[2m]))",
     "legendFormat": "{{entry_point}}----{{name}}--{{tag}}}}"
    }
   ]
  },
  {
   "title": "External IO Exception Rate(No of exceptions / sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(external_io_exception_type{app_name=\"$app_name\", server_ip=\"$server\", entry_point=\"$entry_point\"}[2m]))"
    }
   ]
  },
  {
   "title": "Http Exception Rate(No of exceptions / sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_exception_type{app_name=\"$app_name\", server_ip=\"$server\", entry_point=\"$entry_point\"}[2m]))"
    }
   ]
  },
  {
   "title": "average response time External IO ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (entry_point, name, tag)(rate(external_io_duration_ms_sum{app_name=~\"$app_name\", server_ip=~\"$server\", entry_point=~\"$entry_point\", tag=~\"$io_tag\"}[2m]))\n /\nsum by (entry_point, name, tag)(rate(external_io_duration_ms_count{app_name=~\"$app_name\", server_ip=~\"$server\", entry_point=~\"$entry_point\", tag=~\"$io_tag\"}[2m]))",
     "legendFormat": "{{entry_point}} -- {{name}} -- {{tag}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "locale", "label": "Requests per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{app_name=~\"$app_name\", server_ip=~\"$server\", entry_point=~\"$entry_point\"}[2m]))",
     "legendFormat": "Requests Per Second"
    }
   ]
  },
  {
   "title": "Request Counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_requests_total{app_name=~\"$app_name\", server_ip=~\"$server\", entry_point=~\"$entry_point\"}"
    }
   ]
  },
  {
   "title": "Average response time status wise",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (entry_point, status_code)(rate(http_requests_duration_ms_sum{app_name=~\"$app_name\", server_ip=~\"$server\", entry_point=~\"$entry_point\"}[2m]))\n /\nsum by (entry_point, status_code)(rate(http_requests_duration_ms_count{app_name=~\"$app_name\", server_ip=~\"$server\", entry_point=~\"$entry_point\"}[2m]))",
     "legendFormat": "{{entry_point}}---{{status_code}}"
    }
   ]
  },
  {
   "title": "Average Response Time ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_duration_ms_sum{app_name=~\"$app_name\", server_ip=~\"$server\", entry_point=~\"$entry_point\"}[2m]))\n /\nsum(rate(http_requests_duration_ms_count{app_name=~\"$app_name\", server_ip=~\"$server\", entry_point=~\"$entry_point\"}[2m]))"
    }
   ]
  },
  {
   "title": "Request Rate By status_code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (entry_point, status_code)(rate(http_requests_duration_ms_count{app_name=~\"$app_name\", server_ip=~\"$server\", entry_point=~\"$entry_point\"}[2m]))",
     "legendFormat": "{{entry_point}}-{{status_code}}"
    }
   ]
  },
  {
   "title": "Response Time Distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Requests per sec" }
   ],
   "targets": [
    {
     "expr": "sum by (le)(rate(http_requests_duration_ms_bucket{app_name=~\"$app_name\", server_ip=~\"$server\", entry_point=~\"$entry_point\"}[2m]))"
    }
   ]
  },
  {
   "title": "Response Time Absolute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "http_requests_duration_ms_total{app_name=~\"$app_name\", server_ip=~\"$server\", entry_point=~\"$entry_point\"}",
     "legendFormat": "{{entry_point}}-{{status_code}}"
    }
   ]
  },
  {
   "title": "External IO distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (le)(rate(external_io_duration_ms_bucket{app_name=~\"$app_name\", server_ip=~\"$server\", entry_point=~\"$entry_point\"}[2m]))"
    }
   ]
  },
  {
   "title": "90% SLO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    {
     "format": "short",
     "label": "Fraction of requests rate in 500 ms bucket"
    }
   ],
   "targets": [
    {
     "expr": "sum by (entry_point)(rate(http_requests_duration_ms_bucket{le=\"$slo_duration_sec\", app_name=~\"$app_name\", server_ip=~\"$server\", entry_point=~\"$entry_point\"}[2m]))\n/\n  sum by (entry_point)(rate(http_requests_duration_ms_count{app_name=~\"$app_name\", server_ip=~\"$server\", entry_point=~\"$entry_point\"}[2m]))",
     "legendFormat": "SLO for {{entry_point}}"
    }
   ]
  }
 ]
}